### ISSUE TITLE
Potential import issue in model_io

### ISSUE THREAD

**Issue by joelmeyerson** [aqlaboratory/genie#2]
Should [this import](https://github.com/aqlaboratory/genie/blob/main/genie/utils/model_io.py#L7) be changed from

`from genie.diffusion.Genie import Genie`

to

`from genie.diffusion.genie import Genie` ?

If so, I'd be happy to submit a PR.

**Comment by yeqinglin** [comment]
You are correct. Thanks for pointing this out. I have updated it in the latest commit.
